Her-35-add-product_id-and-product_type-to-order
Code-the-Dream-School/herring-team-3 pull request #29
Opened 2024-12-16 08:08 UTC by dewi-anggraini

HER-35 : Add :product_id and :product_type to Order

## Issue

https://raquelanaroman.atlassian.net/browse/HER-35

Description

We would like to be able to associate an Order with multiple types of Products, not just Kits, so we would like to add a polymorphic relationship to the orders model

Acceptance Criteria
add_reference to orders for product that is polymorphic

## Changes

generate migration to add product to order
updated Kit model, donation model, order model with some validation
updated orders controller

### Review Checklist

- [v] I have documented my code with code comments.

2024-12-16 08:10 UTC, dewi-anggraini commented
before event model

2024-12-16 16:31 UTC, mhope21 requested changes
Looks good, just forgot an "s" that would cause an undefined error.

2024-12-16 16:31 UTC, mhope21 commented on app/models/order.rb
> +  belong_to :product, polymorphic: true
```jsx
belongs_to :product, polymorphic: true
```
Forgot the s.

2024-12-16 16:36 UTC, mhope21 requested changes

2024-12-16 16:36 UTC, mhope21 commented on app/models/kit.rb
> +  has_many :orders, as::product
```jsx
has_many :orders, as: :product
```
Need space between colons, causing linting error.

2024-12-16 16:36 UTC, mhope21 commented on app/models/donation.rb
> +  has_many :orders, as::product
```jsx
has_many :orders, as: :product
```
Need space between colons

2024-12-16 16:39 UTC, mhope21 commented
I am not really sure what is going on with the test check. Maybe we will have to ask Raquel.

2024-12-19 06:51 UTC, mhope21 approved these changes

2024-12-19 06:54 UTC, mhope21 commented
Now you need to get your tests to match your changes.

2025-01-02 04:45 UTC, mhope21 requested changes
Here are a few changes.  Also, there are a bunch of minor corrections in your checks that need to be made, spaces mostly. I updated the brakeman in the last merge with main. So if you update your working branch with the latest main and run bundle install, then your brakeman will update automatically. Let me if you have problems, we may be able to get together on the zoom channel so you can share your screen.

2025-01-02 04:45 UTC, mhope21 commented on spec/factories/orders.rb
> +    end
```
# Define a transient attribute `product` (a `Kit` or `Donation`) with a default value of nil.
# Assign the transient `product` (a `Kit` or `Donation`) to the order after building it.
```

2025-01-02 04:45 UTC, mhope21 commented on app/serializers/order_serializer.rb
> +  attributes :id, :order_name, :order_email, :ordered_kit, :product_type, :product_id :user_id, :school_name, :school_address, :school_year, :comments, :phone, :created_at
`:product_id` needs a comma after it.

2025-01-03 16:58 UTC, raquii requested changes
Make sure to address the errors in your PR!

2025-01-03 16:58 UTC, raquii commented on app/models/order.rb
> +  #belongs_to :kit
remove this instead of commenting out

```suggestion
```

2025-01-03 16:58 UTC, raquii commented on db/migrate/20241231030009_remove_kit_id_from_orders.rb
> +  end
Since we do not expect existing Order records as the app is not yet deployed, lets not include an update script in our migration.

```suggestion
  def change
    remove_column :orders, :kit_id, :integer
  end
```

2025-01-06 16:45 UTC, mhope21 approved these changes
Looks good.

2025-01-07 02:05 UTC, trca831 approved these changes
LGTM!

2025-01-08 18:46 UTC, raquii approved these changes

2025-01-08 19:19 UTC, merged